config/routes.rb
Rails.application.routes.draw do
scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "fr"} do
    get 'pages/home'
    get 'home/index'
    root to: 'pages#home'
    post 'submit', to: 'home#create'
  # Routes liées au SEO
    get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
   get "/robots.:format", to: "pages#robots"

  # # Redirect www to non-www URLs
  match '(*any)', to: redirect(subdomain: 'www'), via: :all, constraints: {subdomain: ''}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :entreprise
  attribute :localisation
  attribute :telephone

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Demande de contact depuis le portfolio de la part de #{name}",
      :to => "julien.gregoire44@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :set_locale


def default_url_options
  { locale: I18n.locale }
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

  private
def set_locale
  I18n.locale = extract_locale || I18n.default_locale
end
def extract_locale
  parsed_locale = params[:locale]
  I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @contact = Home.new(params[:home])
  end

  def create
    @contact = Home.new(params[:home])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Home.new
        format.html { render 'pages/home'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'pages/home' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      def robots
    # Don't forget to delete /public/robots.txt
    respond_to :text
  end

  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController

  layout :false
  before_action :init_sitemap

  def index
    @posts = Post.all
  end

  private

  def init_sitemap
    headers['Content-Type'] = 'application/xml'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/_contact_form.en.html.erb
<%= form_for Home.new, url: submit_path, remote: true do |f| %>
    <div class="col-md-12">
        <%= f.label :Name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Company %></br>
        <%= f.text_field  :entreprise, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Location %></br>
        <%= f.text_field  :entreprise, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Telephone %></br>
        <%= f.text_field  :entreprise, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email%></br>
        <%= f.text_field  :entreprise, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :Message%></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                        placeholder: "Type your message here" %></br>
      <%= f.submit 'Send Message', class: 'button-send' %>
    </div>
  <% end %>
  <div class="col-md-12" id="flash-message">
    <%= render 'home/flash' %>
  </div>

app/views/home/_contact_form.fr.html.erb
<%= form_for Home.new, url: submit_path, remote: true do |f| %>
    <div class="col-md-12">
        <%= f.label :Nom %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Entreprise %></br>
        <%= f.text_field  :entreprise, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Localisation %></br>
        <%= f.text_field  :localisation, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Telephone %></br>
        <%= f.text_field  :telephone, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :Email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :Message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                        placeholder: "Envoyez moi un message" %></br>
      <%= f.submit 'Envoyer message', class: 'button-send' %>
    </div>
  <% end %>
  <div class="col-md-12" id="flash-message">
    <%= render 'home/flash' %>
  </div>

app/views/home/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/home/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/home/index.html.erb
<h1>This is my one page app!</h1>
  <div id="contact">
    <%= render 'contact_form' %>
  </div>

app/views/layouts/application.amp.erb
<!doctype html>
<html ⚡>
  <head>
    <meta charset="utf-8">
    <link rel="canonical" href="<%= url_for(format: :html, only_path: false) %>" >
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <script async custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>
    <% if Rails.application.assets && Rails.application.assets['amp/application'] %>
      <style amp-custom><%= Rails.application.assets['amp/application'].to_s.html_safe %></style>
    <% else %>
      <style amp-custom><%= File.read "#{Rails.root}/public#{stylesheet_path('amp/application', host: nil)}" %></style>
    <% end %>
  </head>
  <body>
    <div class="amp">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <!-- Ajout pour le SEO -->
      <link rel="canonical" href="<%= url_for(format: :html, only_path: false) %>" >
      <link rel="amphtml" href="<%= url_for(format: :amp, only_path: false) %>" >
<!--       fontawesome -->
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
      <!--  Métadonnées -->
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<!-- Ajout polices -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400&family=Roboto&display=swap" rel="stylesheet"
<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
      <!-- autre -->
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all' %>

<!-- Lien vers les 2 versions du site -->
<!-- <nav>
        <ul>
    <li><%= link_to 'Français', root_path(locale: :fr) %></li>
    <li><%= link_to 'English', root_path(locale: :en) %></li>
  </ul>
  </nav> -->
   </head>
   <body>
      <%= yield %>
   </body>

app/views/pages/home.en.html.erb
<div class="wrapper context" id="wrapper">
<section class="section s1" data-anchor="home">
   <div class="text">
      <h1><%= t "hello" %> </h1>
      <div class="phone">
         <p>Si vous êtes ici c'est que vous voulez un aperçu de ce que je suis capable de faire. Pour en savoir plus, je vous invite à descendre afin de découvrir mon parcours, mon expérience, mes projets.</p>
      </div>
   </div>
</section>
<section class="section s2" data-anchor="about">
   <div class="text">
      <h2>A Propos </h2>
      <% dob = Date.new(1990,11,27)
         def age_at(date, dob)
         day_diff = date.day - dob.day
         month_diff = date.month - dob.month - (day_diff < 0 ? 1 : 0)
         date.year - dob.year - (month_diff < 0 ? 1 : 0)
         end  %>
      <%date = Date.today  %>
      <div class="content">
         <p> Je suis un jeune développeur fullstack de
            <%= age_at(date,dob) %> ans.</br></br>
            Après avoir suivi une classe prépa ingénieur à la fin du lycée (j'aime concevoir et créer des solutions aux problèmes que je rencontre),
            j'ai finalement fait un DUT Mesures Physiques qui correspondait mieux à mes attentes de l'époque (un enseignement scientifique basé à la fois sur
            la pratique et la théorie). Une fois diplômé, j'ai travaillé pendant 1an et demi dans un laboratoire d'analyse d'amiante, Eurofins.
            </br></br>
            A la fin de mon contrat, j'ai effectué un premier virage professionnel en travaillant en tant que hotliner en informatique. L'informatique étant un domaine
            qui me passionne, j'ai choisi de me reconvertir en réalisant une formation de développeur web fullstack durant 2 mois au sein de
            <%= link_to 'Le Wagon Lyon', 'https://www.lewagon.com/fr/lyon', target: :_blank %>. J'ai obtenu ma certification en Décembre 2019.
         </p>
      </div>
   </div>
</section>
<section class="s3 section" data-anchor="project">
   <div class="text">
      <h2>Mes réalisations</h2>
      <div class="carousel">
         <ul class="slides">
            <!-- Projet 1 : The Honest meal -->
            <input type="radio" name="radio-buttons" id="img-1" checked />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("Thehonestmeal.jpg", :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "The Honnest Meal",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                     <%= link_to "Projet 1: TheHonnestMeal", 'http://www.thehonestmeal.com/', target: :_blank %>
                     <p>👨‍💻 Ruby - Ruby On Rails - JS - HTML - Chart.js - Geocoder - Cloudinary</br>
                        4 personnes sur le projet pendant 10 jours</br>
                        Le projet réalisé durant ma formation au Wagon
                     </p>
                  </div>
               </div>
               <div class="carousel-controls">
                  <label for="img-3" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-2" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Projet 2 -->
            <input type="radio" name="radio-buttons" id="img-2" />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("LGDG.jpg", :width => :auto, :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "La Gazette des grenouilles",:flags=>"lossy",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                        <%= link_to "Projet 2 : La Gazette des grenouilles", 'http://lagazettedesgrenouilles.fr/', target: :_blank %>
                     </h2>
                     <p>👨‍💻 Wordpress -Contact Form7- Wordpress Importer - WP Telegram</br>
                        Projet personnel pour la communauté d'un jeu auquel je joue
                     </p>
                  </div>
               </div>
               <div class="carousel-controls">
                  <label for="img-1" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-3" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Projet 3 -->
            <input type="radio" name="radio-buttons" id="img-3" />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("LogementsSolidaires.jpg", :width => :auto, :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "Les Logements Solidaires",:flags=>"lossy",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                        <%= link_to "Projet 3 : Les Logements Solidaires", 'https://www.les-logements-solidaires.com/', target: :_blank %>
                     </h2>
                     <p>👨‍💻 Ruby - Ruby On Rails - JS - HTML - SASS - PostgreSQL - Geocoder</br>
                        Organisation de 11 développeurs, 8 développeurs Ruby on Rails (1 Canada, 1 Inde, 6 France) et 2 développeurs Front-end .Temps de développement : 7 jours</br>
                        Projet solidaire realisé avec une equipe d'autres développeurs pour permettre de mettre en lien
                        personnel hospitalier et propriétaires durant la crise du covid-19.
                     </p>
                  </div>
               </div>
               <div class="carousel-controls">
                  <label for="img-2" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-1" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Controller en forme de points -->
            <div class="carousel-dots">
               <label for="img-1" class="carousel-dot" id="img-dot-1"></label>
               <label for="img-2" class="carousel-dot" id="img-dot-2"></label>
               <label for="img-3" class="carousel-dot" id="img-dot-3"></label>
            </div>
         </ul>
      </div>
   </div>
</section>
</section>
<section class="section s4" data-anchor="project">
   <div class="text">
      <h2>Mon CV</h2>
      <%= link_to 'Télécharger mon CV', 'JulienGregoire.pdf', download: '',class: "button-download " %>
   </div>
</section>
<section class="section s5" data-anchor="skills">
   <div class="text">
      <h2>Mes competences</h2>
      <h3>Mes capacités en informatique</h3>
      <p>JS, CSS, HTML, Ruby on rails, git, github, heroku, wordpress</p>
      <h3>Mes autres competences</h3>
      <p>Anglais </br>
         Adaptabilité </br>
         Travail en équipe </br>
         Communication </br>
         A l'écoute
      </p>
   </div>
</section>
<section class="section s6" data-anchor="contact">
   <div class="text">
      <h2>Contact</h2>
      <%= render 'home/contact_form' , index: @contact %>
      <p> <%= t "contact" %></p>
      <span><a href="mailto:julien.gregoire44@gmail.com"><i class="fas fa-sm fa-at fa-2x"></i></a></span>
      <span><a href="https://www.linkedin.com/in/julien-gregoire-42395386" target="_blank"><i class="fab fa-sm fa-linkedin fa-2x"></i></a></span>
      <span><a href="https://www.malt.fr/profile/juliengregoire" target="_blank"> <i><img alt="Malt" src="malt.png"width="26.5" height="30"></i></a></span>
      <span><a href="https://www.facebook.com/JulienGregoireWeb" target="_blank"><i class="fab fa-sm fa-facebook fa-2x"></i></a></span>
      <p> <%= t "thanks" %></p>
   </div>
</section>

app/views/pages/home.fr.html.erb
<section class="section s1" data-anchor="home">
   <div class="text phone">
    <h1>Julien GREGOIRE </br></h1>
      <h2><%= t "devellopeur" %></h2>
   </div>
</section>

<div class="body">
  <div class="about top">
   <div class="text">
      <h2>A Propos </h2>
      <% dob = Date.new(1990,11,27)
         def age_at(date, dob)
         day_diff = date.day - dob.day
         month_diff = date.month - dob.month - (day_diff < 0 ? 1 : 0)
         date.year - dob.year - (month_diff < 0 ? 1 : 0)
         end  %>
      <%date = Date.today  %>
      <div class="content">
         <p>
Je suis un développeur web fullstack de <%= age_at(date,dob) %> ans originaire de St Nazaire.
</br></br>
A la fin du lycée, j’ai commencé par suivre un parcours scientifique en faisant un DUT mesures
physiques. J’ai par la suite effectué divers emplois dans des entreprises différentes,
notamment chez Eurofins au service laboratoire d’analyse. </br></br>
Pendant mon dernier contrat en tant que hotliner SAV en informatique , je me suis rendu
compte que je voulais travailler dans le domaine qui me passionne depuis toujours, le
développement informatique. J’ai donc décidé de me reconvertir en réalisant une formation
intensive de développeur web fullstack au sein de l’organisme de formation
<%= link_to 'Le Wagon Lyon', 'https://www.lewagon.com/fr/lyon', target: :_blank %>.
J'ai obtenu ma certification en décembre 2019 (équivalent à un BAC+2 en informatique).
Depuis lors, j’ai réalisé divers projets, dont ce portfolio, que je vous invite à découvrir.
</br></br>
Ne vous fiez pas à la simplicité de certaines de mes réalisations, je suis capable de
développer des sites bien plus complexes. Je suis passionné par ce que je fais et j’aime
repousser mes limites et optimiser mes projets au maximum.
</br></br>
Si vous le souhaitez, vous pouvez consulter mon CV.
</br></br>
         <%= link_to 'Télécharger mon CV au format PDF', 'JulienGregoireFR.pdf', download: '',class: "button-download " %>
      </div>
   </div>
   </div>

<div class="project middle">
   <div class="text">
      <h2>Mes réalisations</h2>
      <div class="carousel">
         <ul class="slides">
            <!-- Projet 1 : The Honest meal -->
            <input type="radio" name="radio-buttons" id="img-1" checked />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("Thehonestmeal.jpg", :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "The Honnest Meal",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                     <%= link_to "Projet 1: TheHonnestMeal", 'http://www.thehonestmeal.com/', target: :_blank %>
                     <p>👨‍💻 Ruby - Ruby On Rails - JS - HTML - Chart.js - Geocoder - Cloudinary</br>
                        4 personnes sur le projet pendant 10 jours</br>
                        Le projet réalisé durant ma formation au Wagon
                     </p>
                  </div>
              <div class="carousel-controls">
                  <label for="img-3" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-2" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Projet 2 -->
            <input type="radio" name="radio-buttons" id="img-2" />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("LGDG.jpg", :width => :auto, :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "La Gazette des grenouilles",:flags=>"lossy",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                        <%= link_to "Projet 2 : La Gazette des grenouilles", 'http://lagazettedesgrenouilles.fr/', target: :_blank %>
                     </h2>
                     <p>👨‍💻 Wordpress -Contact Form7- Wordpress Importer - WP Telegram</br>
                        Projet personnel pour la communauté d'un jeu auquel je joue
                     </p>
                  </div>
               </div>
               <div class="carousel-controls">
                  <label for="img-1" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-3" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Projet 3 -->
            <input type="radio" name="radio-buttons" id="img-3" />
            <li class="slide-container">
               <div class="slide-image">
                  <%= cl_image_tag("LogementsSolidaires.jpg", :width => :auto, :client_hints => :true, :crop => "scale",
                     :quality => :auto, :sizes => "100vw", :alt => "Les Logements Solidaires",:flags=>"lossy",
                     :loading => "lazy", :fetch_format => :auto) %>
                  <div class="project-text">
                     <h2>
                        <%= link_to "Projet 3 : Les Logements Solidaires", 'https://www.les-logements-solidaires.com/', target: :_blank %>
                     </h2>
                     <p>👨‍💻 Ruby - Ruby On Rails - JS - HTML - SASS - PostgreSQL - Geocoder</br>
                        Organisation de 11 développeurs, 8 développeurs Ruby on Rails (1 Canada, 1 Inde, 6 France) et 2 développeurs Front-end .Temps de développement : 7 jours</br>
                        Projet solidaire realisé avec une equipe d'autres développeurs pour permettre de mettre en lien
                        personnel hospitalier et propriétaires durant la crise du covid-19.
                     </p>
                  </div>
               </div>
               <div class="carousel-controls">
                  <label for="img-2" class="prev-slide">
                  <span>&lsaquo;</span>
                  </label>
                  <label for="img-1" class="next-slide">
                  <span>&rsaquo;</span>
                  </label>
               </div>
            </li>
            <!-- Controller en forme de points -->
            <div class="carousel-dots">
               <label for="img-1" class="carousel-dot" id="img-dot-1"></label>
               <label for="img-2" class="carousel-dot" id="img-dot-2"></label>
               <label for="img-3" class="carousel-dot" id="img-dot-3"></label>
            </div>
         </ul>
      </div>
   </div>
   </div>


<div class="skills bottom">
   <div class="text">
      <h2>Mes competences</h2>
      <h3>Mes capacités en informatique</h3>
      <p>JS, CSS, HTML, Ruby on rails, git, github, heroku, wordpress</p>
      <h3>Mes autres competences</h3>
      <p>Anglais </br>
         Adaptabilité </br>
         Travail en équipe </br>
         Communication </br>
         A l'écoute
      </p>
   </div>
</div>
</div>
<section class="contact s2" data-anchor="contact">
   <div class="text">
      <h2>Contact</h2>
      <%= render 'home/contact_form' , index: @contact %>
      <p> <%= t "contact" %></p>
      <span><a href="mailto:julien.gregoire44@gmail.com"><i class="fas fa-sm fa-at fa-2x"></i></a></span>
      <span><a href="https://www.linkedin.com/in/julien-gregoire-42395386" target="_blank"><i class="fab fa-sm fa-linkedin fa-2x"></i></a></span>
      <span><a href="https://www.malt.fr/profile/juliengregoire" target="_blank"> <i><img alt="Malt" src="malt.png"width="26.5" height="30"></i></a></span>
      <span><a href="https://www.facebook.com/JulienGregoireWeb" target="_blank"><i class="fab fa-sm fa-facebook fa-2x"></i></a></span>
      <p> <%= t "thanks" %></p>
   </div>
</section>